"use client";
import { useEffect,useState } from "react";
import { PortalLayout } from "@/components/PortalLayout";
type Course={id:string;code:string;title:string;unit?:number;level?:number;semester?:string;lecturer?:string};
async function api(action:string,payload:Record<string,unknown>={}){const r=await fetch("/api/admin/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Operation failed");return d}
export default function AdminCourses(){const[courses,setCourses]=useState<Course[]>([]),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");const[f,setF]=useState({code:"",title:"",unit:"3",level:"100",semester:"First"});
async function load(){try{const d=await api("list_courses");setCourses(d.courses||[])}catch(e){setMsg(e instanceof Error?e.message:"Could not load courses")}}useEffect(()=>{load()},[]);
async function save(){setBusy(true);try{await api("create_course",{course:{...f,unit:Number(f.unit),level:Number(f.level)}});setMsg("Course created.");setShow(false);setF({code:"",title:"",unit:"3",level:"100",semester:"First"});await load()}catch(e){setMsg(e instanceof Error?e.message:"Create failed")}finally{setBusy(false)}}
return <PortalLayout role="admin" title="Course Administration"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h1 className="page-title">Courses</h1><p className="muted">Create and manage the university course catalogue.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}>+ Create Course</button></div>{msg&&<div className="card" style={{marginTop:16}}>{msg}</div>}{show&&<div className="card" style={{marginTop:16}}><h2>New course</h2><div className="grid grid-2"><input placeholder="Course code" value={f.code} onChange={e=>setF({...f,code:e.target.value})}/><input placeholder="Course title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input type="number" placeholder="Units" value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}/><input type="number" placeholder="Level" value={f.level} onChange={e=>setF({...f,level:e.target.value})}/></div><div style={{marginTop:12}}><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?"Saving…":"Save Course"}</button> <button className="btn" onClick={()=>setShow(false)}>Cancel</button></div></div>}<div className="card" style={{marginTop:20,overflowX:"auto"}}><table><thead><tr><th>Code</th><th>Title</th><th>Units</th><th>Level</th><th>Semester</th><th>Lecturer</th></tr></thead><tbody>{courses.map(c=><tr key={c.id}><td>{c.code}</td><td>{c.title}</td><td>{c.unit}</td><td>{c.level||"—"}</td><td>{c.semester||"—"}</td><td>{c.lecturer||"—"}</td></tr>)}</tbody></table></div></PortalLayout>}
