"use client";
import {useEffect,useState} from "react";
import {PortalLayout} from "@/components/PortalLayout";
type Exam={id:string;title:string;courseId?:string;durationMinutes?:number;published?:boolean};
async function api(action:string,payload:Record<string,unknown>={}){const r=await fetch("/api/admin/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Operation failed");return d}
export default function AdminExams(){const[exams,setExams]=useState<Exam[]>([]),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");const[f,setF]=useState({title:"",courseId:"",durationMinutes:"30"});
async function load(){try{const r=await fetch("/api/data?action=list_exams");const d=await r.json();setExams(d.exams||[])}catch(e){setMsg(e instanceof Error?e.message:"Could not load exams")}}useEffect(()=>{load()},[]);
async function save(){setBusy(true);try{await api("create_exam",{exam:{...f,durationMinutes:Number(f.durationMinutes),published:false}});setMsg("Exam created as unpublished.");setShow(false);setF({title:"",courseId:"",durationMinutes:"30"});await load()}catch(e){setMsg(e instanceof Error?e.message:"Create failed")}finally{setBusy(false)}}
return <PortalLayout role="admin" title="Examinations"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h1 className="page-title">Examination Control</h1><p className="muted">Create examinations and review their publication state.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}>+ Create Exam</button></div>{msg&&<div className="card" style={{marginTop:16}}>{msg}</div>}{show&&<div className="card" style={{marginTop:16}}><h2>New examination</h2><div className="grid grid-2"><input placeholder="Exam title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input placeholder="Course ID (e.g. csc101)" value={f.courseId} onChange={e=>setF({...f,courseId:e.target.value})}/><input type="number" placeholder="Duration minutes" value={f.durationMinutes} onChange={e=>setF({...f,durationMinutes:e.target.value})}/></div><div style={{marginTop:12}}><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?"Saving…":"Save Exam"}</button> <button className="btn" onClick={()=>setShow(false)}>Cancel</button></div></div>}<div className="card" style={{marginTop:20,overflowX:"auto"}}>{exams.length===0?<p className="muted">No examinations found.</p>:<table><thead><tr><th>Title</th><th>Course</th><th>Duration</th><th>Published</th></tr></thead><tbody>{exams.map(e=><tr key={e.id}><td>{e.title}</td><td>{e.courseId||"—"}</td><td>{e.durationMinutes||"—"} min</td><td>{e.published?"Published":"Draft"}</td></tr>)}</tbody></table>}</div></PortalLayout>}
